[pytest]
pythonpath = .
testpaths =
    tests
addopts = --alluredir=reports/allure-results --clean-alluredir
markers =
    auth: 登录
    course: 课程
    contract: 合同
    clue: 线索
    smoke: 冒烟测试
# 指定用例目录为 tests
;testpaths = niweiming_kdtx

# 识别以 test_ 开头的文件/类/函数
python_files = test_*.py
python_classes = Test*
python_functions = test_*


